-- READ-ONLY USER
DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_roles WHERE rolname = 'readonly_user'
   ) THEN
      CREATE ROLE readonly_user WITH LOGIN PASSWORD 'strongpassword';
   END IF;
END
$$;

GRANT CONNECT ON DATABASE postgres TO readonly_user;
GRANT USAGE ON SCHEMA public TO readonly_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO readonly_user;

ALTER ROLE readonly_user NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;