services:
  app:
    container_name: backend
    image: ${DOCKER_HUB_USERNAME}/database:${APP_IMAGE_TAG:-latest}
    platform: linux/amd64
    ports:
      - "3000:3001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - database_network

networks:
  database_network:
    name: database_network
  
