services:
  postgres:
    container_name: postgres_database
    image: ${DOCKER_HUB_USERNAME}/database-postgres:latest
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=postgres
    ports:
      - ${POSTGRES_PORT_DEV}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - database_volume:/var/lib/postgresql/data
      - ./database/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./database/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./database/postgres/backups/wal_archives:/var/lib/postgresql/wal_archive   # WAL segments land here
      - ./database/postgres/backups/base:/var/lib/postgresql/base_backup          # base backups land here

    networks:
      - database_network

  # the pg-backup service is known as a "sidecar" and is used as to do periodically backups
  pg-backup:
    image: postgres:17
    container_name: postgres_backup
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_BACKUP_USER: ${POSTGRES_BACKUP_USER}
      POSTGRES_BACKUP_PASSWORD: ${POSTGRES_BACKUP_PASSWORD}
    volumes:
      - ./database/postgres/backups/base:/var/lib/postgresql/base_backup
      - ./database/postgres/backups/backup.sh:/usr/local/bin/backup.sh:ro
    networks:
      - database_network
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo "Waiting for first backup in 5 seconds..."
        sleep 5
        while true; do
          bash /usr/local/bin/backup.sh
          echo "Next backup in 24 hours..."
          sleep 86400
        done
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo-standalone
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_DEV}
    volumes:
      - mongo_data:/data/db
    networks:
      - database_network

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474" # Neo4j Browser (GUI)
      - "7687:7687" # Bolt protocol (driver connects here)
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME_DEV}/${NEO4J_PASSWORD_DEV}
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "${NEO4J_USERNAME_DEV}",
          "-p",
          "${NEO4J_PASSWORD_DEV}",
          "RETURN 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - database_network

  neo4j-init:
    image: neo4j:5
    container_name: neo4j_init
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./database/neo4j/cyphers/constraints-and-indexes.cypher:/init/constraints-and-indexes.cypher:ro
    environment:
      NEO4J_USERNAME: ${NEO4J_USERNAME_DEV}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD_DEV}
    networks:
      - database_network
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo "Applying Neo4j constraints and indexes..."
        cypher-shell -a bolt://neo4j:7687 -u $$NEO4J_USERNAME -p $$NEO4J_PASSWORD -f /init/constraints-and-indexes.cypher
        if [ $$? -eq 0 ]; then
          echo "Constraints and indexes applied successfully."
        else
          echo "Failed to apply constraints and indexes."
          exit 1
        fi
    restart: "no"

volumes:
  database_volume:
    name: postgres_data
  mongo_data:
  neo4j_data:

networks:
  database_network:
    name: database_network
