# TYPE    DATABASE        USER            ADDRESS                 METHOD

# Local connections
local     all             all                                     trust

# Standard connections from any host on the docker network
host      all             all             0.0.0.0/0               scram-sha-256

# Replication connections (needed for pg_basebackup)
host      replication     backup_user             0.0.0.0/0               scram-sha-256
hostnossl     replication     backup_user         0.0.0.0/0       scram-sha-256
