password_encryption = scram-sha-256
# pg_cron
cron.database_name = 'postgres'
shared_preload_libraries = 'pg_cron'

# WAL & Archiving
wal_level = replica
archive_mode = on
archive_command = 'cp %p /var/lib/postgresql/wal_archive/%f'
archive_timeout = 60
checkpoint_completion_target = 0.9

# Config files
hba_file = '/etc/postgresql/pg_hba.conf'

# Connection
listen_addresses = '*'      # listen on all interfaces, including docker network
